### ISSUE TITLE
Update Repository.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [LopyMine/Texturized-Particles#1]
Hello!

I've found out that in Modrinth File there's `lang/xx_xx.json` (i. e. Language Files) presented, but in this Repository I didn't find it.
Also I can't find any mention of those Strings that appear in Mod's YACL Configs.
![Screenshot](https://github.com/user-attachments/assets/e78047b3-02d4-44f9-a45f-dcc1b1bffc47)

So, for Me it looks like that this Repository should be updated.

**Comment by LopyMine** [comment]
Hmm, oh, looks like you right, let me upload mod translations 😄

**Comment by LopyMine** [comment]
Uploaded 👍
So, about string, what do you mean by *any mention*?

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Uploaded 👍 So, about string, what do you mean by _any mention_?

I thought that in this Source Code there's no mention of strings' addresses, but I'm not sure.
It would be great if You correct Me.

**Comment by LopyMine** [comment]
Do you mean a key for text from jsons? If so, then it creates from other smaller strings

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Do you mean a key for text from jsons? If so, then it creates from other smaller strings

I mean that I can't find "...option.mod_enabled.X" Address or something like that in Source Code... may be there's other Translation String System Code.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
Ok, thank You!
