### ISSUE TITLE
Bumblezone and Texturized-Particles can cause the game to collapse

### ISSUE THREAD

**Issue by SanQianQVQ** [LopyMine/Texturized-Particles#3]
https://github.com/TelepathicGrunt/Bumblezone/issues/451 

Log: https://mclo.gs/rDzismL

**Comment by SanQianQVQ** [comment]
In addition, I really like this mod, which makes minecraft more vivid

**Comment by LopyMine** [comment]
What you did to cause the game to crash? This will help me recreate it and find the crash reason

**Comment by SanQianQVQ** [comment]
> What you did to cause the game to crash? This will help me recreate it and find the crash reason

I did nothing, but the block game where my base was located collapsed. From the log, it seemed to be the potion candle of Bumblezone, and this MOD related

**Comment by LopyMine** [comment]
Hmm, okay. I don't have enought time to fix that right now, but I will fix it a little bit later 👌

**Comment by TelepathicGrunt** [comment]
For reference, I am spawning Minecraft’s potion effect particle like this. This wasn’t any custom particle but rather me reusing an existing particle:

https://github.com/TelepathicGrunt/Bumblezone/blob/2dc4c2034f1d9caf52cbe4c798754721b4895039/common/src/main/java/com/telepathicgrunt/the_bumblezone/blocks/PotionCandleBase.java#L308

**Comment by TelepathicGrunt** [comment]
Also be aware my mod does have some custom potion effects such as paralysis or hidden or beenergized. Just double check that your mod can handle modded status effects without issue

**Comment by LopyMine** [comment]
I tested Texturized Particles with Visuallity and it worked fine. I'm guessing something went wrong during the color <-> particle registration stage, causing it to receive a null object and throw an NullPointerException. So, I just need some time to test it and find issue reason

**Comment by LopyMine** [comment]
Should be fixed in 1.0.1 👍
Let me know if crashes will happens again
